import { useEffect, useState } from 'react'
import type { DailyDigest, DigestIndex } from './types/digest'
import DigestTabs from './components/DigestTabs'
import DigestView from './components/DigestView'

const BASE = import.meta.env.BASE_URL

export default function App() {
  const [dates, setDates] = useState<string[]>([])
  const [activeDate, setActiveDate] = useState<string | null>(null)
  const [digest, setDigest] = useState<DailyDigest | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    fetch(`${BASE}data/index.json`)
      .then(r => r.json())
      .then((idx: DigestIndex) => {
        setDates(idx.dates)
        if (idx.dates.length > 0) setActiveDate(idx.dates[0])
        else setLoading(false)
      })
      .catch(() => {
        setError('No digest data yet. Check back after the first scheduled run.')
        setLoading(false)
      })
  }, [])

  useEffect(() => {
    if (!activeDate) return
    setLoading(true)
    setDigest(null)
    fetch(`${BASE}data/${activeDate}.json`)
      .then(r => r.json())
      .then((d: DailyDigest) => {
        setDigest(d)
        setLoading(false)
      })
      .catch(() => {
        setError('Failed to load digest for this date.')
        setLoading(false)
      })
  }, [activeDate])

  return (
    <div className="min-h-screen bg-zinc-950">
      {/* Header */}
      <header className="border-b border-zinc-800 px-6 py-5">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <div>
            <h1 className="text-lg font-semibold tracking-tight text-zinc-100">
              E-Bike Daily Digest
            </h1>
            <p className="text-xs text-zinc-500 mt-0.5 font-mono">
              Top 10 from Reddit · Updated 09:00 CST
            </p>
          </div>
          <span className="text-xs font-mono text-brand-500 border border-brand-500/30 bg-brand-500/10 px-2 py-1 rounded">
            LIVE
          </span>
        </div>
      </header>

      {/* Date Tabs */}
      {dates.length > 0 && (
        <DigestTabs
          dates={dates}
          activeDate={activeDate!}
          onSelect={setActiveDate}
        />
      )}

      {/* Content */}
      <main className="max-w-4xl mx-auto px-4 py-8">
        {loading && (
          <div className="flex items-center justify-center py-24">
            <div className="w-6 h-6 border-2 border-brand-500 border-t-transparent rounded-full animate-spin" />
          </div>
        )}
        {error && !loading && (
          <div className="text-center py-24">
            <p className="text-zinc-500 font-mono text-sm">{error}</p>
          </div>
        )}
        {digest && !loading && <DigestView digest={digest} />}
      </main>

      <footer className="border-t border-zinc-800 px-6 py-4 mt-8">
        <div className="max-w-4xl mx-auto text-center text-xs text-zinc-600 font-mono">
          Data sourced from Reddit · Generated by Claude · Keeps 7 days of history
        </div>
      </footer>
    </div>
  )
}
